config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  
  resources :users do
    resource :profile
    resources :interests
  end
  resources :topics
  
  resources :interests
  
  resources :contacts
  resources :early_invites
  get '/about' => 'pages#about'
  
  root 'early_invites#new'
  
  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :comments, presence: true
end

app/models/early_invite.rb
class EarlyInvite < ActiveRecord::Base
  validates :email, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  
  def self.group_interests(interests)
    interest_groups = [[], [], []]
    
    interests.each do |interest|
      case interest.experience_level
        when 1 then interest_groups[0].push(interest)
        when 2 then interest_groups[1].push(interest)
        when 3 then interest_groups[2].push(interest)
      end
    end
    interest_groups
  end

end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :interests
  has_many :users, through: :interests
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  attr_accessor :stripe_card_token
  
  has_many :interests
  has_many :topics, through: :interests
  
  
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :stripe_card_token, :email, :password, :password_confirmation])
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
   
   def new
       @contact = Contact.new
   end
   
   def create
       @contact = Contact.new(contact_params)
       
       if @contact.save
           name = params[:contact][:name]
           email = params[:contact][:email]
           body = params[:contact][:comments]
           
           ContactMailer.contact_email(name, email, body).deliver
           flash[:success] = "Message sent."
           redirect_to new_contact_path
       else
           flash[:danger] = "Error occured, message has not been sent."
           redirect_to new_contact_path
       end
   end
   
   private
       def contact_params
           params.require(:contact).permit(:name, :email, :comments)
       end
end

app/controllers/early_invites_controller.rb
class EarlyInvitesController < ApplicationController
  def new
    @coming_soon = 1
    @early_invite = EarlyInvite.new
  end
  
  def create
    @coming_soon = 1
    @early_invite = EarlyInvite.new(early_invite_params)
    if @early_invite.save
      flash[:early_invite_thanks] = "Thank you! You're now on the early access list."
      redirect_to new_early_invite_path
    else
      flash[:early_invite_error] = "Please enter a valid email address and try again."
      redirect_to new_early_invite_path
    end
  end
  
  private
    def early_invite_params
      params.require(:early_invite).permit(:email)
    end
  
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  respond_to :html, :json
 
  def show 
    @interest = Interest.find(params[:id])
  end
  
  def new
    # Form where a user can add a new interest.
    @interest = Interest.new
  end
 
  def update
    @interest = Interest.find(params[:id])
    # @interest.update_attributes(params[:interest])
    
    if @interest.update_attributes(interest_params)
      flash[:warning] = "Interest updated!"
      # redirect_to user_path( params[:user_id] )
    # else
    #   render action: :edit
    end
    
    respond_with @interest
  end

  def destroy
    @interest = Interest.find(params[:id])
    @interest.destroy
    
    redirect_to(current_user) 
    #redirect_to action: :index
  end

  private
    def interest_params
      params.require(:interest).permit(:interest_description, :experience_level)
    end
    #def only_current_user
    #  @user = User.find( params[:user_id] )
    #  redirect_to(root_url) unless @user == current_user
    #end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @basic_plan = Plan.find(1)
        @premium_plan = Plan.find(2)
    end
    
    def about
        
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_current_user
  def new
    # Form where a user can fill out their own profile.
    @user = User.find( params[:user_id] )
    @profile = Profile.new
  end
  
  def create
    @user = User.find( params[:user_id] )
    @profile = @user.build_profile(profile_params)
    if @profile.save
      flash[:success] = "Profile created!"
      redirect_to user_path( params[:user_id] )
    else
      render action: :new
    end
  end
  
  def edit
    @user = User.find( params[:user_id] )
    @profile = @user.profile
  end
  
  def update
    @user = User.find( params[:user_id] )
    @profile = @user.profile
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile updated!"
      redirect_to user_path( params[:user_id] )
    else
      render action: :edit
    end
  end
  
  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :avatar, :description)
    end
    def only_current_user
      @user = User.find( params[:user_id] )
      redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
   before_action :select_plan, only: :new
   
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
  end
  
  private
    def select_plan
      unless params[:plan] && (params[:plan] == "1" || params[:plan] == "2")
        # flash[:notice] = "Please select a membership plan to sign up."
        redirect_to root_url
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  respond_to :html, :json
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find( params[:id] )
    @user_check = (@user == current_user)
#    if @user_check == true
#      flash[:success] = "Looking at my own page! (users controller)"
#    else
#      flash[:success] = "Looking at someone else's page! (users controller)"
#    end
    @interests = @user.interests
    @interest_groups = Interest.group_interests(@interests)
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-md-2 vertical-title-section">
    <div id="contact-title" class="vertical vertical-title">
      <h1>Contact us</h1>
    </div>
  </div>
  <div class="col-md-4 content-section">
    <div class="well content-well" id="contact-form">
      <%= form_for @contact do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
            
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
            
        <div class="form-group">
          <%= f.label :comments %>
          <%= f.text_area :comments, class: 'form-control' %>
        </div>
        <%= f.submit "Send", class: 'btn btn-green' %>
      <% end %>
    </div>
  </div>
</div>

app/views/early_invites/new.html.erb
<div class="hero text-center">
  <%= image_tag("bitSpokes_logo_white_big.png") %>
  <h2>Bike in the cloud</h2>
  
  <h3 id="comingsoon-tagline">A new app for bicyclists is coming!
  <br>Sign up for early access.</h3>
  <%= form_for @early_invite, :url => { :action => "create" } do |f| %>
    <%= f.email_field :email, :placeholder => "Enter Email", :class => "email earlyinvite" %>
    <input class="submit earlyinvite" name="commit" type="submit" value="Sign me up!" />
  <% end %>
  <p id="early-invite-footer">We promise to never spam you.</p>
</div>

app/views/interests/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Add a new interest</h1>
    <div class="well">
      
      <%= form_for @interest, url: new_interest_path, html: { multipart: true } do |f| %>
  
        <%= f.fields_for :topic do |topic_form| %>
          <%= topic_form.label :interest_topic %>
          <%= topic_form.collection_select( :topic_id, Topic.all, :id, :topic_name) %>
        <% end %>
        
        <div class="form-group">
          <%= f.label :experience_level %>
          <%= f.select( :experience_level,[['beginner', 1],['intermediate', 2],['expert',3]]) %>
        </div>
        
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :interest_description, class: 'form-control' %>
        </div>
        <div class="form-group btn-profile-submit">
          <%= f.submit "Add", class: 'btn btn-green' %>
        </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>bitSpokes</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<div id="bkgd-container">
  <!-- Bootstrap navbar -->
  <nav class="navbar navbar-inverse navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <% if user_signed_in? %>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <% end %>
        
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag("bitSpokes_name_w_logo_small_1.png") %>
        <% end %>
      </div>
  
      <% if user_signed_in? %>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-green navbar-btn' %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Community", users_path %></li>
            <li><%= link_to "My Account", edit_user_registration_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->  
          
      <% elsif "coming_soon".nil? %>
        <div class="nav navbar-nav navbar-right">
          <%= link_to "Log in", new_user_session_path, class: 'btn navbar-btn', method: :get %>
        </div>
      <% end %>
        
    </div><!-- /.container-fluid -->
  </nav>
  
  <div class="container-fluid padded-wrapper">
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
    <% end %>
    <%= yield %>
  </div>
  
  
  
    
  <!--FOOTER SECTION -->
  <footer class="footer" id="footer"> 
    <div class="container">
  	  <div id="footer-links">
  	    <%= link_to "About", about_path %>
        <i class="fa fa-circle footer-delimiter" aria-hidden="true"></i>
        <%= link_to "Contact us", new_contact_path %>
  	  </div>
  		<p id="footer-copyright">
  			Copyright 
  			<i class="fa fa-copyright" aria-hidden="true"></i> 
  			2016
  			<script>
  				new Date().getFullYear()>2016&&document.write("- "+new Date().getFullYear());
  			</script> 
  			bitSpokes.com <i class="fa fa-circle footer-delimiter" aria-hidden="true"></i> All Rights Reserved
  		</p>
    </div>
  </footer>
  <!--END FOOTER SECTION --> 
</div>


</body>
</html>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-md-2 vertical-title-section">
    <div id="about-title" class="vertical vertical-title">
      <h1>About</h1>
    </div>
  </div>
  <div class="col-md-4 content-section">
    <div class="well content-well" id="about-blurb">
      <h3>
        <span class="bit-word">bit</span>Spokes is a social app for bicyclists.
      </h3>
      <p>
        Team up with your existing bike friends, or find new ones with similar biking interests.
        Share bikes, trails, gear and tips, all in one place.
      </p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="hero text-center">
  <%= image_tag("bitSpokes_logo_white_big.png") %>
  <h2>Bike in the cloud</h2>
  <div class="row">
    <div class="col-md-6 tagline-left">
      <h3>Team up.</h3>
    </div>
    <div class="col-md-6 tagline-right">
      <h3>Share <div class="share-text-box" id="share-things"></div></h3>
    </div>
  </div>
  <%= link_to "Sign up for free", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-lg signup-button' %>
</div>

<div class="row">
  <% if user_signed_in? %>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Your profile</h2>
        <% if current_user.profile %>
          <%= link_to "Edit your profile", edit_user_profile_path(current_user), class: 'btn btn-primary btn-lg btn-block' %>
          <%= link_to "View your profile", user_path(current_user), class: 'btn btn-primary btn-lg btn-block' %>
        <% else %>
          <%= link_to "Create your profile", new_user_profile_path(current_user), class: 'btn btn-primary btn-lg btn-block' %>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center"></h2>
        <p></p>
        <%= link_to "Visit the community", users_path, class: 'btn btn-primary btn-lg btn-block' %>
      </div>
    </div>
  <% else %>
    
      
    
    <!--
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Premium Membership</h2>
        <h4>Sign up for the premium account for $1/month and get access to the community and extra features</h4>
        <%= link_to "Sign up for Premium", new_user_registration_path(plan: @premium_plan.id), class: 'btn btn-success btn-lg btn-block' %>
      </div>
    </div>
    -->
    
    
  <% end %>

</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :bio %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group btn-profile-submit">
    <%= f.submit "Submit", class: 'btn btn-green' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1 class="text-center">Edit your profile</h1>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create your profile</h1>
    <p class="text-center">Hey, fill out your profile!</p>
    <div class="well">
      <%= form_for @profile, url: user_profile_path do |f| %>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Profile", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_contact_me.html.erb
<div class="menu-item-contact hide-menu-item">
  <p class="social-media-group">
    <i class="fa fa-envelope fa-2x" aria-hidden="true"></i>
    <i class="fa fa-facebook-square fa-2x" aria-hidden="true"></i>
    <i class="fa fa-instagram fa-2x" aria-hidden="true"></i>
  </p>
</div>

app/views/users/_dashboard.html.erb
<div class="menu-item-dashboard">
  <div class="row">
    <div class="col-md-4">
      <div class="menu-item-bar">
        <h2>Action center</h2>
      </div>
      <div class="well well-inverse">
        <ul>
          <li><a href="#">Complete your profile</a></li>
          <li><a href="#">Join a team</a></li>
        </ul>
      </div>
    </div>
    <div class="col-md-7">
      <h2>Recent activity</h2>
      <div class="activity-container well well-inverse">
          <ul>
            <li>Updated profile on September 27th, 2016.</li>
            <li>Joined bitSpokes on August 27th, 2016.</li>
          </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/_inventory.html.erb
<div class="menu-item-inventory hide-menu-item">
  <p class="inventory-group">
    Inventory placeholder
  </p>
</div>

app/views/users/_short_profile.html.erb
<div class="menu-item-profile hide-menu-item">
  <div class="row">
    <div class="col-md-6">
      <div id="profile-about-section">
        <div class="menu-item-bar">
          <h2>About <%= link_to "Edit", edit_user_profile_path(current_user), class: 'btn btn-green btn-edit-profile' %>
          </h2>
        </div>
        <div class="well well-inverse">
          <p><%= @user.profile.description %></p>
          <p class="timestamp">Joined <%= @user.profile.created_at.strftime("%B %d, %Y") %></p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <h2>
      Interests
      <!-- <span class="btn-add">
        <i class="fa fa-plus-square-o fa-1x" aria-hidden="true"></i>
      </span>
      -->
      <%= link_to "Add", new_interest_path, class: 'btn btn-green btn-edit-profile' %>
    </h2>
      <div class="interests-container">
        <% @interest_groups.reverse.each_with_index do |interest_group, ind| %>
          <% if ind == 0 then %>
            <div class="expert-interests">
          <% elsif ind == 1 then %>
            <div class="intermediate-interests">
          <% else %>
            <div class="beginner-interests">
          <% end %>
          
          <% if not interest_group.empty? then %>
            
            <% interest_group.each do |interest| %>
              <div class="interest pointer">
                <div class="interest-bar">
                  <h4>
                    <%= interest.topic.topic_name %>
                  </h4>
                  <% if @user == current_user %>
                  <span class="btn-edit toggle">
                    <i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i>
                  </span>
                  <span class="btn-save hide">
                    <i class="fa fa-check fa-2x" aria-hidden="true"></i>
                  </span>
                  <% end %>
                </div>
                <div class="interest-exp-level toggle hide" id="interest-exp-level-<%=interest.id%>">
                  <!--
                  <% if ind == 0 then %>
                    expert
                  <% elsif ind == 1 then %>
                    intermediate
                  <% else %>
                    beginner
                  <% end %>
                  -->
                  <%= best_in_place interest, 
                    :experience_level, 
                    :as => :select, 
                    :collection => [[1, 'beginner'], [2, 'intermediate'], [3, 'expert']],
                    :html_attrs => { :style => 'color: green; width: 185px;' },
                    :activator => '#interest-exp-level-' + interest.id.to_s 
                  %>
                </div>
                <span class="btn-delete-container hide">
                  <%= button_to interest_path(interest), method: :delete, data: {confirm: "Delete this interest?"}, class: 'btn-delete' do %>
                    
                  <i class="fa fa-times fa-2x" aria-hidden="true"></i>
                  <% end %>
                  
                </span>
                <div class="interest-description-empty hide">
                  <p class="interest-description toggle" id="interest-description-<%=interest.id%>">
                    <!-- <%= interest.interest_description %> -->
                    <%= best_in_place interest, 
                      :interest_description, 
                      :as => :textarea,
                      :html_attrs => { :style => 'width:235px; height:85px;' },
                      :place_holder => 'Click here to add notes',
                      :activator => '#interest-description-' + interest.id.to_s
                    %>
                  </p>
                 </div>
              </div>
            <% end %>
            
          <% end %>
            </div>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <ul class="list-unstyled">
      <% @users.each do |user| %>
        <% if user.profile %>
          <li>
            <div class="well row <%= cycle('grey-bg', '') %>">
              <div class="col-sm-4 text-center">
                <%= link_to user do %>
                  <%= image_tag user.profile.avatar.url(:thumb), class: 'user-index-avatar' %>
                <% end %>
              </div>
              <div class="col-sm-4">
                <%= link_to user do %>
                  <h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
                  <% if user.plan_id == 2%>
                    <span class="label label-danger">PREMIUM</span>
                  <% end %>
                <% end %>
                <p></p>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-2 vertical-title-section">
    <div id="user-title" class="vertical vertical-title">
      <% if @user == current_user %>
        <h1>Me</h1>
      <% end %>
    </div>
  </div>
  
  
  <div class="col-md-8 content-section">
    <div class="well content-well" id="user-content">
  
      <div class="row user-page-header">
        <div class="col-md-2">
          <div class="text-center">
            <%= image_tag @user.profile.avatar.url, class: 'user-show-avatar' %>
          </div>
          <div class="well well-menu-vert">
            <ul class="menu-vert" id="profile-menu">
              <li class="menu-item-dashboard selected-bkgd">Dashboard</li>
              <li class="menu-item-profile">Profile</li>
              <li class="menu-item-account">Account</li>
              <li class="menu-item-inventory">Inventory</li>
              <li class="menu-item-history">History</li>
              <li class="menu-item-contact">Contact me</li>
              <li class="menu-item-team">Team</li>
            </ul>
          </div>
        </div>
        <div class="col-md-10">
          <div id="name-header">
            <h2>
              <strong>
                <%= @user.profile.first_name %>
                <%= @user.profile.last_name %>
              </strong>
            </h2>
            <h4>
              Team <a href="#">Me, myself and I</a>
              in <a href="#">Boston, MA</a>
            </h4>
          </div>
          <div class="profile-menu-items">
            <%= render "dashboard" %>
            <%= render "short_profile" %>
            <%= render "account" %>
            <%= render "inventory" %>
            <%= render "history" %>
            <%= render "contact_me" %>
          </div> <!-- profile menu items -->
        </div>
    
      </div>

    </div>
  </div>
</div>